name: Maven Central Repo Deployment
on:
  release:
    types: [ released ]
jobs:
  publish-central:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          server-id: central
          server-username: SERVER_USERNAME
          server-password: SERVER_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Publish to Apache Maven Central
        run: mvn deploy
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}